### PR TITLE
feat(async): embed 'ms-jpq/lua-async-await' as 'async' module

### PR DESCRIPTION
**Pull request by linrongbin16**

### CODE REVIEW

**Comment by linrongbin16** [comment]
requirement from: https://github.com/linrongbin16/gitlinker.nvim/issues/181

**Comment by lopi-py** [comment]
Actually, I'm already doing it with some tweaks so we don't need to call `async.await` and `async.wrap` everywhere.

**Comment by linrongbin16** [comment]
> Actually, I'm already doing it with some tweaks so we don't need to call `async.await` and `async.wrap` everywhere.

OK, so we don't need the lua-async-await library?

**Comment by lopi-py** [comment]
> OK, so we don't need the lua-async-await library?

Not really, I'm taking care of it.

**Comment by linrongbin16** [comment]
> > OK, so we don't need the lua-async-await library?
> 
> Not really, I'm taking care of it.

cool!

**Pull request merged**
